### ISSUE TITLE
Google reCAPTCHA not showing in forms

### ISSUE THREAD

**Issue by chrisfox75** [ultimatemember/recaptcha#13]
I recently installed this plugin for Ultimate member and i am using Google reCAPTCHA v3 and i have the keys installed properly, have each of my forms enabled for captcha and for some reason the captcha is not showing on the forms in the live preview or on the live site page for the form, i have 4 forms 3 are the default that UM installed and the fourth is one i have created, but none of them show the captcha even though enabled.

As an FYI i have noticed a few people commenting about this same issue they are having on the wordpress.org forums for the plugin

Thank you for your help

**Comment by chrisfox75** [comment]
Someone on the wordpress.org forums mentioned that the captcha information for v3 is indeed there but it was hiding behind my cookie information popup in the lower right hand corner of the screen, im assuming this is how it works since the documentation does not state that.

Thank you

**Comment by nikitasinelnikov** [comment]
Hi @chrisfox75 

Sorry for delay. I didn't get any notice about opened issue. You can try to play around CSS styles for the reCAPTCHA block to make it visible. But v3 reCAPTCHA is invisible and there isn't any form field that is visible for the user. 

reCAPTCHA block is situated in the right bottom corner https://jam.dev/c/44538c72-0e04-46c4-891e-a27e3ffbf56e
