### ISSUE TITLE
Password is incorrect. Please try again

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/recaptcha#7]
Read this UM Support Forum thread:
https://wordpress.org/support/topic/password-is-incorrect-please-try-again/

with a solution here by @zufusion:
https://wordpress.org/support/topic/password-is-incorrect-please-try-again/page/3/#post-16050440

**Comment by NiitoCHKN** [comment]
@MissVeronica i have read the solution, but can you say me where is that code? in which file? thank you

**Comment by MissVeronica** [comment]
@NiitoCHKN This issue has been posted in the wrong repository, I will make a new issue in the UM repository and also post a code snippet which you can try and give feedback about your results.

**Comment by MissVeronica** [comment]
@NiitoCHKN You should never replace code in the UM core scripts you will loose the changes at the next UM version update

**Comment by NiitoCHKN** [comment]
@MissVeronica so how can i solve this problem?

**Comment by MissVeronica** [comment]
This is is moved to https://github.com/ultimatemember/ultimatemember/issues/1091
